source "git@github.com:CocoaPods/Specs.git"

# ignore all warnings from all pods
# inhibit_all_warnings!

target 'PayHousekeeper' do
    platform :ios, '7.0'
    
    pod 'SDWebImage', '3.7.6'
    pod 'FMDB', '2.6'
    pod 'Toast', '3.0'
#    pod 'SVProgressHUD', '2.0.3'
#    pod 'NIMSDK','3.0.0'
    pod 'Reachability', '~> 3.1.1'
    pod 'IQKeyboardManager'
    pod 'GPUImage', '0.1.6'
    pod 'pop'
    pod 'UMengAnalytics-NO-IDFA','4.1.9'
    pod 'SSZipArchive'
end

